name: MkDocs Deploy

on:
  push:
    branches: master
    paths: 
      - 'docs/**/*.md'
      - 'mkdocs.yml'

jobs:
  deploy:
    runs-on: windows-latest
    
    steps:
      - name: Git config
        run: |
          git config --global core.symlinks true
          git config --global user.name "github-actions"
          git config --global user.email actions@github.com
          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          feach-depth: 0
 
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv --upgrade-strategy=only-if-needed
          pipenv install --dev
          
      - name: MkDocs deploy
        run: |
          git featch --depth=1 origin master
          pipenv run mkdocs gh-deploy
        
