name: MkDocs Deploy

on:
  push:
    branches: master
    paths:
      - "docs/**/*.md"
      - "mkdocs.yml"
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email actions@github.com

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install pipenv and libpq
        run: |
          sudo apt-get install libpq-dev -y
          pip install pipenv

      - name: Cache pipenv virtualenv
        id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: pipenv install

      - name: MkDocs deploy
        run: |
          git fetch --depth=1 origin master
          pipenv run mkdocs gh-deploy
